### ISSUE TITLE
actor Scoreのサンプルの実行結果について

### ISSUE THREAD

**Issue by takehilo** [SatoTakeshiX/first-step-swift-concurrency#3]
ご著書に大変お世話になっております！素晴らしい本をありがとうございます！

以下のサンプルコードについて質問です。
https://github.com/SatoTakeshiX/first-step-swift-concurrency/blob/main/try-concurrency.playground/Pages/2-3-actor.xcplaygroundpage/Contents.swift

Playgroundで以下を実行すると確かに`100`→`110`の順に出力されるのですが、それは①→②→③→④の順番に実行された場合であり、①→③→②→④の順に実行されることもあるのではないかと思ったのですが、その可能性はありますか？
その場合、`110`→`110`という出力になる気がしています。
ただ、Playgroundで何度実行しても`100`→`110`になるので、手元で再現はできていません。

actorによってscoreに同時にアクセスできるスレッドは1つに保証されていますが、`update(with:)`を呼んだ後、同じタスク（スレッド）がすぐに`highScore`にアクセスできる保証はないと思っているのですが、認識間違っていますでしょうか？

```swift
Task.detached {
    await score.update(with: 100)  // ①
    print(await score.highScore)   // ②
}

Task.detached {
    await score.update(with: 110)  // ③
    print(await score.highScore)   // ④
}
```

**Comment by SatoTakeshiX** [comment]
@takehilo さん、質問ありがとうございます。

> ①→③→②→④の順に実行されることもあるのではないかと思ったのですが、その可能性はありますか？

はい、このサンプルコードではおっしゃる通り、 ①→③→②→④の順で実行される可能性はあります。
`Task.detached` が２つあるので、２つのタスクが一つの `score` インスタンスを扱っている形になります。
その際も `await` があるところではアクセスできるスレッドは一つだけなので、データ競合が起こらない形になっています。

> update(with:)を呼んだ後、同じタスク（スレッド）がすぐにhighScoreにアクセスできる保証はないと思っているのですが、認識間違っていますでしょうか？


ですです。その認識であっています。 ①→③→②→④のように①でupdateした後に③のupdateが実行される可能性はあります。

ただし、XcodeのPlaygroundでは`Task.detached` を複数記述しても上から実行されるような挙動になっていました。
実行結果としては、必ず①→②→③→④になるようです。

実行結果が①→③→②→④もありうるというものの確認は[Swift Playgrounds](https://www.apple.com/jp/swift/playgrounds/)を使うと良いようです。

Swift Playgroundsで以下のように`Task.detached` の数を増やして確認すると「同じタスク（スレッド）がすぐにhighScoreにアクセスできる保証はない」ことがわかります。

```swift
actor Score {
    var logs: [Int] = []
    private(set) var highScore: Int = 0
    
    func update(with score: Int) {
        logs.append(score)
        if score > highScore {
            highScore = score
        }
    }
}

let score = Score()

/*:
 actorを使うと必ず100, 110の結果が得られる
 */
Task.detached {
    await score.update(with: 100)
    print(await score.highScore)
}

Task.detached {
    await score.update(with: 110)
    print(await score.highScore)
}

Task.detached {
    await score.update(with: 120)
    print(await score.highScore)
}

Task.detached {
    await score.update(with: 130)
    print(await score.highScore)
}
Task.detached {
    await score.update(with: 140)
    print(await score.highScore)
}
Task.detached {
    await score.update(with: 150)
    print(await score.highScore)
}
Task.detached {
    await score.update(with: 160)
    print(await score.highScore)
}
```

実行するたびに結果は変わります。
あるときに結果はこのような感じでした。

```
//結果
100
140
160
160
160
160
160
```

一番最後に記述した `await score.update(with: 160)` が3番目に呼ばれたのでprint文のoutputの3番目以降が160になってました。

**Comment by SatoTakeshiX** [comment]
ちなみにXcodeのplaygroundでは何度実行しても上から順に実行されているようでした。

```
//結果
100
110
120
130
140
150
160
```

**Comment by takehilo** [comment]
ご回答ありがとうございます！
Swift Playgroundsを使うという発想はなかった...Xcode Playgroundだとうまく再現できないんですね...
自分の手元でも、Swift Playgroundsを使うと想定通りの動きとなりました。
ありがとうございます！
